### ISSUE TITLE
ERROR: no such package '@com_google_asylo_toolchain//toolchain 

### ISSUE THREAD

**Issue by kamathhrishi** [google/asylo#33]
ERROR: no such package '@com_google_asylo_toolchain//toolchain': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/6f5dfd08c182635f43c28327b7ed358d/external/com_google_asylo/asylo/bazel/asylo_deps.bzl", line 94
		installation_path(repository_ctx, "default_toolchain...", <3 more arguments>)
	File "/root/.cache/bazel/_bazel_root/6f5dfd08c182635f43c28327b7ed358d/external/com_google_asylo/asylo/bazel/installation_path.bzl", line 71, in installation_path
		_fail_if_directory_does_not_exist(repository_ctx, result, what)
	File "/root/.cache/bazel/_bazel_root/6f5dfd08c182635f43c28327b7ed358d/external/com_google_asylo/asylo/bazel/installation_path.bzl", line 23, in _fail_if_directory_does_not_exist
		fail(((("Install path to " + what) + ...))
Install path to Asylo toolchain [default] [INTERNAL TRANSITION] does not exist: /opt/asylo/toolchains/sgx_x86_64

**Comment by deeglaze** [comment]
It appears that you are attempting to run outside the docker container. Please run the asylo/distrib/toolchain/install-toolchain script to install the cross-compiler that Asylo requires to build enclave binaries.

**Comment by kamathhrishi** [comment]
Yeah I realized. Thank you :)
