### ISSUE TITLE
bazel sync errors in docker

### ISSUE THREAD

**Issue by ipetr0v** [google/asylo#53]
I'm trying to run `bazel sync` to download Asylo's dependencies in docker, but get the following error:
```
INFO: Repository 'six_archive' used the following cache hits instead of downloading the corresponding file.
 * Hash '105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a' for https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
If the definition of 'six_archive' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'six_archive':
   Traceback (most recent call last):
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/bazel_tools/tools/build_defs/repo/http.bzl", line 57
                workspace_and_buildfile(ctx)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Not a regular file: /.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_google_protobuf/six.BUILD
```

My `WORKSPACE` looks like this:
```
workspace(name = "asylo_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_asylo",
    sha256 = "7f53d61d91a8d6963a5665088b02129d643a4cfbcab883f1076b71bcbe07184d",
    strip_prefix = "asylo-088ea3490dd4579655bd5b65b0e31fe18de7f6dd",
    urls = [
        # Head commit on 2019-11-21.
        "https://github.com/google/asylo/archive/088ea3490dd4579655bd5b65b0e31fe18de7f6dd.tar.gz",
    ],
)

load("@com_google_asylo//asylo/bazel:asylo_deps.bzl", "asylo_deps", "asylo_go_deps")
asylo_deps()
asylo_go_deps()

load("@com_google_asylo//asylo/bazel:sgx_deps.bzl", "sgx_deps")
sgx_deps()
```
And my `Dockerfile` looks like this:
```
FROM gcr.io/asylo-framework/asylo:buildenv-v0.5.0
```

**Comment by KeithMoyer** [comment]
Thanks for the report, @ipetr0v !

It looks like protobuf moved the six.BUILD file to a different folder; we missed this because this dependency actually became unused recently in Asylo. We'll get it removed from asylo_deps().

**Comment by ipetr0v** [comment]
@KeithMoyer Another thing that I have found is, when I add:
```
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
```
to a `WORKSPACE` file, I also get this error in docker after running `bazel sync`:
```
INFO: Call stack for the definition of repository 'local_config_python' which is a python_configure (rule definition at /.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl:294:20):
 - /.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/bazel/grpc_python_deps.bzl:57:5
 - /.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:233:5
 - /opt/my-project/WORKSPACE:22:1
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 281
                _create_single_version_package(<5 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 255, in _create_single_version_package
                _symlink_genrule_for_dir(<4 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 119, in _symlink_genrule_for_dir
                "\n".join(<1 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 120, in "\n".join
                sorted(<1 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 120, in sorted
                _read_dir(repository_ctx, <1 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 81, in _read_dir
                _execute(repository_ctx, <2 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 56, in _execute
                _fail(<1 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 28, in _fail
                fail(<1 more arguments>)
Python Configuration Error: Repository command failed
find: '/usr/include/python2.7': No such file or directory
```
This error is fixed after I install `python-dev` in docker, but then I get the following error:
```
ERROR: Traceback (most recent call last):
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 286
                _create_single_version_package(<5 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 254, in _create_single_version_package
                _get_python_include(<2 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 217, in _get_python_include
                _execute(repository_ctx, <3 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 56, in _execute
                _fail(<1 more arguments>)
        File "/.cache/bazel/_bazel_ivanpetrov/b6bc0828d5b43c7085b650e0698bf388/external/com_github_grpc_grpc/third_party/py/python_configure.bzl", line 28, in _fail
                fail(<1 more arguments>)
Python Configuration Error: Problem getting python include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.7/distutils/__init__.py)
Is the Python binary path set up right? (See ./configure or PYTHON2_BIN_PATH.) Is distutils installed?
```
That is fixed by also installing `python3-dev`.
Does it mean, that docker image should also contain `python-dev` and `python3-dev` ?

**Comment by KeithMoyer** [comment]
Asylo itself doesn't require those to build, but it doesn't seem unreasonable to add python*-dev packages to the container. I'll look into making that change as well.

I wasn't familiar with `bazel sync`. I had always used `bazel fetch //...` (or similar) to fetch all of the dependencies. Interesting. Thanks!
